const typeTranslations = {
    "normal": "normal", "fire": "feuer", "water": "wasser", "grass": "pflanze",
    "electric": "blitz", "ice": "eis", "fighting": "kampf", "poison": "gift",
    "ground": "boden", "flying": "flug", "psychic": "psy", "bug": "insekt",
    "rock": "gestein", "ghost": "geist", "dragon": "drache", "steel": "stahl",
    "fairy": "fee"
};

const germanToEnglish = {
    "bisasam": "bulbasaur", "bisaknosp": "ivysaur", "bisaflor": "venusaur", 
    "glumanda": "charmander", "glutexo": "charmeleon", "glurak": "charizard", 
    "schiggy": "squirtle", "schillok": "wartortle", "turtok": "blastoise", 
    "raupy": "caterpie", "safcon": "metapod", "smettbo": "butterfree", 
    "hornliu": "weedle", "kokuna": "kakuna", "bibor": "beedrill", 
    "taubsi": "pidgey", "tauboga": "pidgeotto", "tauboss": "pidgeot", 
    "rattfratz": "rattata", "rattikarl": "raticate", "habitak": "spearow", 
    "ibitak": "fearow", "rettan": "ekans", "arbok": "arbok", 
    "pikachu": "pikachu", "raichu": "raichu", "sandan": "sandshrew", 
    "sandamer": "sandslash", "nidoran♀": "nidoran-f", "nidorina": "nidorina", 
    "nidoqueen": "nidoqueen", "nidoran♂": "nidoran-m", "nidorino": "nidorino", 
    "nidoking": "nidoking", "piepi": "clefairy", "pixi": "clefable", 
    "vulpix": "vulpix", "vulnona": "ninetales", "pummeluff": "jigglypuff", 
    "knuddeluff": "wigglytuff", "zubat": "zubat", "golbat": "golbat", 
    "myrapla": "oddish", "duflor": "gloom", "giflor": "vileplume", 
    "paras": "paras", "parasek": "parasect", "bluzuk": "venonat", 
    "omot": "venomoth", "digda": "diglett", "digdri": "dugtrio", 
    "mauzi": "meowth", "snobilikat": "persian", "enton": "psyduck", 
    "entoron": "golduck", "menki": "mankey", "rasaff": "primeape", 
    "fukano": "growlithe", "arkani": "arcanine", "quapsel": "poliwag", 
    "quaputzi": "poliwhirl", "quappo": "poliwrath", "abra": "abra", 
    "kadabra": "kadabra", "simsala": "alakazam", "machollo": "machop", 
    "maschock": "machoke", "machomei": "machamp", "knofensa": "bellsprout", 
    "ultigaria": "weepinbell", "sarzenia": "victreebel", "tentacha": "tentacool", 
    "tentoxa": "tentacruel", "kleinstein": "geodude", "georok": "graveler", 
    "geowaz": "golem", "ponita": "ponyta", "gallopa": "rapidash", 
    "flegmon": "slowpoke", "lahmus": "slowbro", "magnetilo": "magnemite", 
    "magneton": "magneton", "porenta": "farfetchd", "dodu": "doduo", 
    "dodri": "dodrio", "jurob": "seel", "jugong": "dewgong", 
    "sleima": "grimer", "sleimok": "muk", "muschas": "shellder", 
    "austos": "cloyster", "nebulak": "gastly", "alpollo": "haunter", 
    "gengar": "gengar", "onix": "onix", "traumato": "drowzee", 
    "hypno": "hypno", "krabby": "krabby", "kingler": "kingler", 
    "voltobal": "voltorb", "lektrobal": "electrode", "owei": "exeggcute", 
    "kokowei": "exeggutor", "tragosso": "cubone", "knogga": "marowak", 
    "kicklee": "hitmonlee", "nockchan": "hitmonchan", "schlurp": "lickitung", 
    "smogon": "koffing", "smogmog": "weezing", "rihorn": "rhyhorn", 
    "rizeros": "rhydon", "chaneira": "chansey", "tangela": "tangela", 
    "kangama": "kangaskhan", "seeper": "horsea", "seemon": "seadra", 
    "goldini": "goldeen", "golking": "seaking", "sterndu": "staryu", 
    "starmie": "starmie", "pantimos": "mr-mime", "sichlor": "scyther", 
    "rossana": "jynx", "elektek": "electabuzz", "magmar": "magmar", 
    "pinsir": "pinsir", "tauros": "tauros", "karpador": "magikarp", 
    "garados": "gyarados", "lapras": "lapras", "ditto": "ditto", 
    "evoli": "eevee", "aquana": "vaporeon", "blitza": "jolteon", 
    "flamara": "flareon", "porygon": "porygon", "amonitas": "omanyte", 
    "amoroso": "omastar", "kabuto": "kabuto", "kabutops": "kabutops", 
    "aerodactyl": "aerodactyl", "relaxo": "snorlax", "arktos": "articuno", 
    "zapdos": "zapdos", "lavados": "moltres", "dratini": "dratini", 
    "dragonir": "dragonair", "dragoran": "dragonite", "mewtu": "mewtwo", 
    "mew": "mew"
};